apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: booking-platform

resources:
  - base/namespace.yml
  - base/secrets.yml
  - base/postgres.yml
  - base/rabbitmq.yml
  - services/booking-service.yml
  - services/seat-service.yml
  - services/payment-service.yml
  - services/ticket-service.yml
  - services/notification-service.yml
  - monitoring/jaeger.yml
  - monitoring/prometheus.yml
  - monitoring/grafana.yml
  - monitoring/otel-collector.yml
