loopback_users = none
listeners.tcp.default = 5672
management.tcp.port = 15672

# Heartbeat
heartbeat = 30

# Memory & Disk
vm_memory_high_watermark.relative = 0.8
disk_free_limit.relative = 2.0

# Dead Letter Exchange defaults
default_vhost = /

# Load definitions (exchanges, queues, bindings)
management.load_definitions = /etc/rabbitmq/definitions.json
