apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: booking-platform
type: Opaque
stringData:
  username: postgres
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: booking-platform
type: Opaque
stringData:
  username: guest
  password: guest
